Fix FileObserver constructor crash on < API 26
Call getAbsolutePath() to pass a String to the constructor,
which is compatible with Android Nougat and all subsequent versions.

Fix for < API 26:

java.long.NoSuchMethodError: No direct method <init>(Ljava/io/File;)V
in class Landroid/os/FileObserver; or its super classes